### PR TITLE
#186103247 : APIController is no longer a singleton

### PR DESCRIPTION
**Pull request by qmjava**

### CODE REVIEW

**Review by dgilling — CHANGES_REQUESTED** [review]
What about removing the static ApplicationId?

**Comment by qmjava** [comment]
well, if that is the case, We need to make Configuration object instanceable

**Comment by dgilling** [comment]
@qmjava what I suggest is:
1. MoesifAPIClient holds a reference to an instance of Configuration, APIController, and HealthController. These can be created in the constructor.
2. When creating these we also need to pass in the ApplicationId, so so the children controllers have the ApplicationId
3. Calling getAPI() or getHealth() will return these references, rather than call getInstance()

**Comment by praves77** [comment]
@dgilling ^^^ it looks good to me.

**Review by dgilling — APPROVED** [review]

**Pull request merged**
